package StringMath;

enum Operation {
	ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION, MODULO,
	LESS_THAN, /*LESS_THAN_OR_EQUAL_TO,*/ GREATER_THAN, /*GREATER_THAN_OR_EQUAL_TO,*/ EQUAL_TO, /*NOT_EQUAL_TO*/
}